replicaCount: 1
strategyType:
deploymentApiVersion: apps/v1

image:
  registry: FILLED_IN_BY_CI
  tag: FILLED_IN_BY_CI

  pullPolicy: IfNotPresent
  secrets:
    - name: ecr-registry

podAnnotations: {}

application:
  secretName:
  secretChecksum:

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

service:
  enabled: true
  annotations: {}
  name: web
  type: ClusterIP
  additionalHosts:
    - scp.biomage.net
  externalPort: 5000
  internalPort: 5000

ingress:
  tls:
    enabled: true
    secretName: ""
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    kubernetes.io/ingress.class: "nginx"
  modSecurity:
    enabled: false
    secRuleEngine: "DetectionOnly"
    # secRules:
    #   - variable: ""
    #     operator: ""
    #     action: ""

prometheus:
  metrics: false

livenessProbe:
  path: "/"
  initialDelaySeconds: 15
  timeoutSeconds: 15
  scheme: "HTTP"
  probeType: "httpGet"

readinessProbe:
  path: "/"
  initialDelaySeconds: 5
  timeoutSeconds: 3
  scheme: "HTTP"
  probeType: "httpGet"

resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
  requests:
#    cpu: 100m
#    memory: 128Mi

## Configure PodDisruptionBudget
## ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
podDisruptionBudget:
  enabled: false
  # minAvailable: 1
  maxUnavailable: 1

## Configure NetworkPolicy
## ref: https://kubernetes.io/docs/concepts/services-networking/network-policies/
networkPolicy:
  enabled: false
  spec:
    podSelector:
      matchLabels: {}
    ingress:
    - from:
      - podSelector:
          matchLabels: {}
      - namespaceSelector:
          matchLabels:
            # add some namespace selectors here

# SHOULD BE FILLED IN BY THE CI SYSTEM
biomageCi:
  ref: refs-heads-master
  repo: biomage-ltd/ui

kubernetes:
  env: production