{{- if and (.Values.service.enabled) (eq .Values.biomageCi.ref "refs-heads-master") -}}
apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  name: {{ template "appname" . }}
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version| replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

  annotations:
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
{{- with .Values.ingress.modSecurity }}
{{- if .enabled }}
    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$server_name-$request_id"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRuleEngine {{ .secRuleEngine | default "DetectionOnly" | title }}
{{- range $rule := .secRules }}
{{ (include "secrule" $rule) | indent 6 }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.prometheus.metrics }}
    nginx.ingress.kubernetes.io/server-snippet: |-
      location /metrics {
          deny all;
      }

{{- end }}

spec:

{{- if .Values.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ template "hostname" . }}
{{- if .Values.service.additionalHosts }}
{{- range $host := .Values.service.additionalHosts }}
    - {{ $host }}
{{- end -}}
{{- end }}
    secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" (include "appname" .)) }}
{{- end }}
  rules:
  - host: {{ printf "%s.scp.biomage.net" (split "/" .Values.biomageCi.repo)._1 }}
    http:
      &httpRule
      paths:
      - path: /
        backend:
          serviceName: {{ template "appname" . }}
          servicePort: {{ .Values.service.externalPort }}
{{- if .Values.service.additionalHosts }}
{{- range $host := .Values.service.additionalHosts }}
  - host: {{ $host }}
    http:
      <<: *httpRule
{{- end -}}
{{- end -}}
{{- end -}}
